#!/bin/bash

HOME=/home/xaos/gmal
export DISPLAY=:0 

GPU_T=$(aticonfig --adapter=all --odgt | grep -i sensor | cut -d - -f 2)
MB_T=$(sensors | grep -i temp | grep ^MB | sed "s|\\s\\s\\+| |g" | cut -d " " -f 3)

$HOME/notify "GPU: $GPU_T, MB: $MB_T"
