#!/bin/bash

HOME=/home/xaos/gmal

if [ $(whoami) == "root" ]
then
  sudo -u xaos $HOME/monit
  exit
fi


export DISPLAY=:0

GPU0_T=$(aticonfig --odgt --adapter=0 | grep -i sensor | cut -d - -f 2)
GPU1_T=$(aticonfig --odgt --adapter=1 | grep -i sensor | cut -d - -f 2)

MB_T=$(sensors | grep -i temp | grep ^MB | sed "s|\\s\\s\\+| |g" | cut -d " " -f 3)

MEM=$(free -m | grep ^Mem | sed "s|\\s\\s\\+| |g" | cut -d " " -f 2-4)
SWAP=$(free -m | grep ^Swap | sed "s|\\s\\s\\+|/|g" | cut -d "/" -f 3-4)

$HOME/notify "GPUs: $GPU0_T, $GPU1_T. MB: $MB_T. Swap: $SWAP."
