#!/bin/bash

HOME=/home/xaos/gmal

NAME=$(cat $HOME/name 2>/dev/null)
[ -z "$NAME" ] && NAME="rest"

fortune=$(fortune)

$HOME/ttytter -keyf=$HOME/ttytter.key -status="[$NAME] $* | $fortune" >/dev/null 2>&1
